parameters:
  - name: feed_name
    type: string
  - name: package_name
    type: string
  - name: extra_index_url
    type: string

jobs:
- job: PaaWorkflow
  displayName: 'Package-auto-assembler workflow'
  pool:
    vmImage: 'ubuntu-latest'

  steps:

  - checkout: self
    persistCredentials: true 
    fetchDepth: '15'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
      addToPath: true   
    displayName: 'Set up Python'

  - script: |
      sudo apt-get update && sudo apt-get install jq
    displayName: 'Install jq'

  - script: |
      chmod +x .azure/tools/assemble_pypirc.sh
      chmod +x .azure/tools/assemble_pip_conf.sh
      .azure/tools/assemble_pypirc.sh
      .azure/tools/assemble_pip_conf.sh ${{ parameters.extra_index_url }}
      cp .pypirc ~/.pypirc
    displayName: 'Assemble .pypirc from vars amd pip_conf'
    env:
      TWINE_PASSWORD: $(TWINE_PASSWORD)

  - script: |
      sudo apt-get update
      sudo apt-get install -y wget xvfb libnotify4 libxml2-utils
      wget https://github.com/jgraph/drawio-desktop/releases/download/v24.6.4/drawio-amd64-24.6.4.deb
      sudo dpkg -i drawio-amd64-24.6.4.deb
      sudo apt-get install -f
    displayName: 'Install Draw.io Desktop and Dependencies'

  - script: |
      python -m pip install --upgrade pip
      pip install -r .paa/requirements_dev.txt
    displayName: 'Install Python Dependencies'

  - script: |
      paa convert-drawio-to-png --label-name ${{ parameters.package_name }}
    displayName: 'Export drawio files to png files'

  - script: |
      git pull origin main
    displayName: 'Pull latest changes from the remote repository'

  - script: |
      paa make-package ${{ parameters.package_name }}
    displayName: 'Assemble and build package'

  - task: TwineAuthenticate@1
    inputs:
      artifactFeed: ${{ parameters.feed_name }}
    displayName: 'Twine Authenticate'

  - script: |
      python -m twine upload -r ${{ parameters.feed_name }} dist/*.whl --verbose
    displayName: 'Upload to feed'
    env:
      TWINE_USERNAME: $(TWINE_USERNAME)
      TWINE_PASSWORD: $(TWINE_PASSWORD)

  - script: |
      chmod +x .azure/tools/update_README.sh
      .azure/tools/update_README.sh
    displayName: 'Update README'

  

  