name: Update README

on:
  # push:
  #   branches:
  #     - main
  workflow_run:
      workflows: ["Generate PlantUML Diagrams"]
      types:
        - completed

jobs:
  documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install python dependencies
        run: pip install -r env_spec/requirements.txt

      - name: Add Python Kernel
        run: python -m ipykernel install --user --name python3

      - name: Generate md files from jupyter
        run: |
          ./tools/convert_ipynb_to_markdown.sh

      - name: Update README.md
        run: |
          ./tools/update_README.sh

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull origin HEAD:main
          git add docs README.md
          # Check if there are any changes in the working directory
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update README"
            git push
          else
            echo "No changes to commit"
          fi
