name: Update README

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'Name of the package'
        required: false
        default: 'package_auto_assembler'

jobs:
  documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetches prev commits

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Find Changed Modules
        id: changed-modules
        run: |

          if [ "${{ github.event.inputs.package_name }}" != "" ]; then
            echo "${{ github.event.inputs.package_name }}" > changed_files
          else
            chmod +x .github/tools/find_and_process_changed_files.sh
            .github/tools/find_and_process_changed_files.sh 'python_modules/' 'drawio/' 'example_notebooks/' '' ''
          fi

          if [ -s changed_files ]; then
              echo "::set-output name=files::$(cat changed_files)"
          fi

      - name: Install Draw.io Desktop and Dependencies
        if: steps.changed-modules.outputs.files != ''
        run: |
          sudo apt-get update
          sudo apt-get install -y wget xvfb libnotify4 libxml2-utils
          wget https://github.com/jgraph/drawio-desktop/releases/download/v24.6.4/drawio-amd64-24.6.4.deb
          sudo dpkg -i drawio-amd64-24.6.4.deb
          sudo apt-get install -f

      - name: Export drawio files to png files
        if: steps.changed-modules.outputs.files != ''
        run: |
          chmod +x .github/tools/convert_drawio_to_png.sh
          .github/tools/convert_drawio_to_png.sh "drawio/${{ steps.changed-modules.outputs.files }}.drawio"


      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install python dependencies
        run: pip install -r .paa/requirements_dev.txt

      # - name: Add Python Kernel
      #   run: python -m ipykernel install --user --name python3

      - name: Generate md files from jupyter for changed modules
        if: steps.changed-modules.outputs.files != ''
        run: |
          chmod +x .github/tools/convert_ipynb_to_markdown.sh
          .github/tools/convert_ipynb_to_markdown.sh "example_notebooks/${{ steps.changed-modules.outputs.files }}.ipynb"

      - name: Update README.md
        run: |
          chmod +x .github/tools/update_README.sh
          .github/tools/update_README.sh

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull origin HEAD:main
          git add .paa/docs README.md
          # Check if there are any changes in the working directory
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update README"
            git push
          fi
