name: Update README

on:
  push:
    branches:
      - main

jobs:
  documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update README.md
        run: |
          ./tools/update_README.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *
          git commit -m "Update README"
          git push
