name: Update README

on:
  push:
    branches:
      - main

jobs:
  documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install python dependencies
        run: pip install -r env_spec/requirements.txt

      - name: Generate Plantuml
        run: ./tools/generate_uml_diagrams.sh

      - name: Install Graphviz
        run: sudo apt-get install graphviz

      - name: Download PlantUML
        run: wget http://sourceforge.net/projects/plantuml/files/plantuml.jar/download -O plantuml.jar

      - name: Generate UML Diagrams
        run: |
          ./tools/generate_uml_diagrams.sh

      - name: Generate md files from jupyter
        run: |
          ./tools/convert_ipynb_to_markdown.sh

      - name: Update README.md
        run: |
          ./tools/update_README.sh

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs README.md plantuml
          # Check if there are any changes in the working directory
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update README"
            git push
          else
            echo "No changes to commit"
          fi
