name: Init README Update

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'python_modules/**'
      - 'tools/extract_requirements.py'
      - 'tools/update_requirements.sh'
      - 'tools/update_module_requirements.sh'


jobs:
  init_readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3