name: Linter

on:
  pull_request:

jobs:
  pr_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Replace with the Python version you need

      - name: Install python dependacies
        run: pip install -r env_spec/requirements.txt

      - name: Install pylint
        run: pip install pylint

      - name: Run Linter Test
        run: |
          ./tools/pylint_test.sh
