name: Publish packages

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'Name of the package'
        required: false


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 15  # Fetches prev commits

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install jq

      - name: Find Changed Modules
        id: changed-modules
        run: |
          if [ "${{ github.event.inputs.package_name }}" != "" ]; then
            echo "${{ github.event.inputs.package_name }}" > changed_files
          else
            chmod +x .github/tools/find_and_process_changed_files.sh
            chmod +x .github/tools/get_paa_change_dirs.sh
            .github/tools/find_and_process_changed_files.sh $(.github/tools/get_paa_change_dirs.sh) '' ''
          fi

          if [ -s changed_files ]; then
              echo "::set-output name=files::$(cat changed_files)"
          fi

      - name: Set up Python 3.10
        if: steps.changed-modules.outputs.files != ''
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Create and activate virtual environment
        if: steps.changed-modules.outputs.files != ''
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        if: steps.changed-modules.outputs.files != ''
        run: |
          python -m pip install --upgrade pip
          pip install -r .paa/requirements_dev.txt

      - name: Pull latest changes from the remote repository
        if: steps.changed-modules.outputs.files != ''
        run: git pull origin main

      - name: Save module requirements
        if: steps.changed-modules.outputs.files != ''
        run: paa extract-module-requirements "${{ steps.changed-modules.outputs.files }}" > ".paa/requirements/requirements_${{ steps.changed-modules.outputs.files }}.txt"

      - name: Assemble and build package
        if: steps.changed-modules.outputs.files != ''
        run: |

          echo "Assembling for:"
          echo ${{ steps.changed-modules.outputs.files }}
          # echo "Test-installing paa ..."
          # paa test-install package-auto-assembler
          echo "Assembling..."
          paa make-package ${{ steps.changed-modules.outputs.files }}
          ls -la

      - name: Publish to PyPI
        if: steps.changed-modules.outputs.files != ''
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          ls -la
          python -m twine upload dist/*

      - name: Commit changes
        if: steps.changed-modules.outputs.files != ''
        run: |
          set -x

          PACKAGE_VERSION=$(paa extract-tracking-version "${{ steps.changed-modules.outputs.files }}")
          if [ -z "${PACKAGE_VERSION}" ]; then
            echo "Failed to get version"
            exit 1
          fi

          LABEL_NAME=$(basename "${{ steps.changed-modules.outputs.files }}" .py)

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git pull origin HEAD:main

          git add .paa

          # Check if there are any changes in the working directory
          if [ -n "$(git status --porcelain)" ]; then
            COMMIT_MESSAGE="Update package version tracking files"
            TAG_NAME="v${PACKAGE_VERSION}_${LABEL_NAME}"
            TAG_MESSAGE="${LABEL_NAME}==${PACKAGE_VERSION}"

            git commit -m "${COMMIT_MESSAGE}"
            git tag -a "${TAG_NAME}" -m "${TAG_MESSAGE}"
            git push origin HEAD:main
            git push origin "${TAG_NAME}"
          else
            echo "No changes to commit"
          fi


