name: Extract requirements

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:

  extract-requirements:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2  # Fetches prev commits

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Find Changed Modules
      id: changed-modules
      run: |
        echo "Changed files:"
        changed_files=$(git diff --name-only HEAD~ HEAD | grep 'python_modules/')
        echo $changed_files
        echo "::set-output name=files::${changed_files}"

    - name: Install Dependencies
      run: |
        pip install -r env_spec/requirements_dev.txt

    - name: Update requirements for changed modules
      run: |
        .github/tools/update_module_requirements.sh ${{ steps.changed-modules.outputs.files }}
        .github/tools/update_requirements.sh


    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add env_spec/*
        # Check if there are any changes in the working directory
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Update requirements"
          git push
        else
          echo "No changes to commit"
        fi
