name: Tests

on:
  pull_request:
    paths:
      - 'python_modules/**'
      - 'tests/**'

jobs:

  update-requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r env_spec/requirements_dev.txt

      - name: Update requirements
        run: |
          ./tools/update_module_requirements.sh
          ./tools/update_requirements.sh

      - name: Check requirements for vulnerabilities
        run: |
          ./tools/check_for_vulnerabilities.sh

      - name: Upload updated requirements
        uses: actions/upload-artifact@v2
        with:
          name: updated-requirements
          path: env_spec/requirements.txt

  test:
    needs: update-requirements
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download updated requirements
        uses: actions/download-artifact@v2
        with:
          name: updated-requirements
          path: env_spec/

      - name: Install dependencies
        run: pip install -r env_spec/requirements_dev.txt

      - name: Test with tox
        run: tox

