name: Tests

on:
  pull_request:
    paths:
      - 'python_modules/**'
      - 'tests/**'

jobs:

  update-requirements:
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.changed-modules.outputs.files }}
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 15  # Fetches prev commits

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Find Changed Modules
        id: changed-modules
        run: |
          if [ "${{ github.event.inputs.package_name }}" != "" ]; then
            echo "${{ github.event.inputs.package_name }}" > changed_files
          else
            chmod +x .github/tools/find_and_process_changed_files.sh
            .github/tools/find_and_process_changed_files.sh 'cli/' 'python_modules/' '' ''
          fi

          if [ -s changed_files ]; then
              echo "::set-output name=files::$(cat changed_files)"
          fi

      - name: Install dependencies
        if: steps.changed-modules.outputs.files != ''
        run: pip install -r .paa/requirements_dev.txt

      - name: Update requirements
        if: steps.changed-modules.outputs.files != ''
        run: |
          chmod +x .github/tools/update_module_requirements.sh
          chmod +x .github/tools/update_tox_requirements.sh
          python -m pip install setuptools wheel twine
          .github/tools/update_module_requirements.sh "${{ steps.changed-modules.outputs.files }}"
          .github/tools/update_tox_requirements.sh "${{ steps.changed-modules.outputs.files }}"
          cat .paa/requirements/requirements_tox.txt 

      - name: Check requirements for vulnerabilities
        if: steps.changed-modules.outputs.files != ''
        run: |
          #./tools/check_for_vulnerabilities.sh
          paa check-vulnerabilities "${{ steps.changed-modules.outputs.files }}"


      - name: Check module licenses
        if: steps.changed-modules.outputs.files != ''
        run: |
          paa check-licenses "${{ steps.changed-modules.outputs.files }}"

      - name: Upload updated requirements
        if: steps.changed-modules.outputs.files != ''
        uses: actions/upload-artifact@v4
        with:
          name: updated-requirements
          path: .paa/requirements/requirements_tox.txt

  test:
    needs: update-requirements
    if: needs.update-requirements.outputs.changed-files != ''
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download updated requirements
        uses: actions/download-artifact@v4
        with:
          name: updated-requirements
          path: .paa/requirements/

      # - name: Cache pip dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.cache/pip
      #     key: ${{ runner.os }}-pip-${{ hashFiles('env_spec/requirements_tox.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pip-

      - name: Install dependencies
        run: | 
          pip install -r .paa/requirements_dev.txt

      - name: Test with tox
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            if [ -d "tests/${{ needs.update-requirements.outputs.changed-files }}" ]; then
              tox -- "tests/${{ needs.update-requirements.outputs.changed-files }}"
            else
              echo "No tests for module."
            .github/tools/pylint_test.sh
            fi
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            if [ -d "tests/${{ needs.update-requirements.outputs.changed-files }}" ]; then
              tox -- "tests/${{ needs.update-requirements.outputs.changed-files }}"
            else
              echo "No tests for module."
            fi
          fi
        shell: bash